name: 'Generate Auto Changelog'
on:
    push:
        branches:
            - master
jobs:
    master:
        name: 'build'
        runs-on: ubuntu-latest
        steps:
            - name: Generate Auto Changelog
              uses: ahmadawais/action-auto-changelog@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
